name: Stable Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  stable-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Current Version
        id: version
        run: |
          version=$(cat VERSION)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Increment Version
        id: increment_version
        run: |
          old_version=${VERSION}
          new_version=$(echo $old_version | awk -F. '{$NF += 1; OFS="."; print $0}')
          echo "$new_version" > VERSION
          echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

      - name: Commit New Version
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add VERSION
          git commit -m "Bump version to v${{ env.NEW_VERSION }}"
          git push

      - name: Create Stable Release
        run: |
          gh release create "v${{ env.NEW_VERSION }}" \
            --title "Release v${{ env.NEW_VERSION }}" \
            --notes "Automated release from main branch." \
            || echo "Release already exists"

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
