#!/bin/bash

. "$GRPL_WORKDIR/constants"

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  OS=gnu
elif [[ "$OSTYPE" == "darwin"* ]]; then
  OS=mac
elif [[ "$OSTYPE" == "cygwin" ]]; then
  OS=posix
elif [[ "$OSTYPE" == "msys" ]]; then
  OS=lw
elif [[ "$OSTYPE" == "freebsd"* ]]; then
  OS=freebsd
else
  OS=unknown
fi

cli_log() {
  script_name=${0##*/}
  timestamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
  echo "== $script_name $timestamp $1"
}

exit_on_interrupt() {
    echo; echo -e "${RED}Script interrupted by user. Exiting...${NC}" >&2
    status_log $TYPE_ERROR "Script interrupted by user. Exiting..."
    exit 130
}


# calling syntax : status_log <type> <message>
# supported types : TYPE_INFO, TYPE_SUCCESS, TYPE_ERROR, TYPE_DEFAULT
status_log() {

  # first select color
  log_color=""
  if [ $1 == $TYPE_INFO ]; then log_color=$info_color
  elif [ $1 == $TYPE_SUCCESS ]; then log_color=$success_color
  elif [ $1 == $TYPE_ERROR ]; then log_color=$error_color
  elif [ $1 == $TYPE_DEFAULT ]; then log_color=$reset_color
  fi

  gum log "$(printf "${log_color}${2}${reset_color}")"

}

# check and install all pre-requsite packages
install_prerequisite(){


  # if OS is gnu, we want to check and install snap
  # this package will be used to install other packages in future
  if [ $OS == "gnu" ] && ! snap version >/dev/null 2>&1; then
    sudo apt update
    sudo apt install snapd
  fi


  # installing helm
  if ! helm version >/dev/null 2>&1; then
    echo "helm is a prerequisite for this script to run."
    echo "installing helm..."
    if [ $OS == "mac" ]; then 
      gum spin --title "a prerequisite helm is not installed, now installing helm" --show-output -- brew install helm
    elif [ $OS == "gnu" ]; then
      gum spin --title "a prerequisite helm is not installed, now installing helm" --show-output -- sudo snap install helm --classic
    else
      errMsg="Failed to install a prerequisite helm, OS ${OS} not supported at the moment"
      echo $errMsg
      status_log $TYPE_ERROR $errMsg
      exit 1
    fi
  fi

  if ! kubectl version >/dev/null 2>&1; then
    echo "kubectl is a prerequisite for this script to run."
    echo "installing kubectl..."
    if [ $OS == "mac" ]; then 
      gum spin --title "a prerequisite kubectl is not installed, now installing kubectl" --show-output -- brew install kubectl
    elif [ $OS == "gnu" ]; then
      gum spin --title "a prerequisite kubectl is not installed, now installing kubectl" --show-output -- sudo snap install kubectl --classic
    else
      errMsg="Failed to install a prerequisite kubectl, OS ${OS} not supported at the moment"
      echo $errMsg
      status_log $TYPE_ERROR $errMsg
      exit 1
    fi
  fi

  # Ensure gum is installed: https://github.com/charmbracelet/gum
  if ! gum --version >/dev/null 2>&1; then
    echo "gum is a prerequisite for this script to run."
    echo "installing gum..."
    if [ "${OS}" == "mac" ]; then
      gum spin --title "a prerequisite gum is not installed, now installing gum" --show-output -- brew install gum
    elif [ "${OS}" == "gnu" ]; then 
      sudo mkdir -p /etc/apt/keyrings
      curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
      echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
      gum spin --title "a prerequisite gum is not installed, now installing gum" --show-output -- sudo apt update && sudo apt install gum
      sudo ln -s /usr/bin/gum /snap/bin/gum
    else
      errMsg="Failed to install a prerequisite gum, OS ${OS} not supported at the moment"
      echo $errMsg
      status_log $TYPE_ERROR $errMsg
      exit 1
    fi
  fi
}

# need to create log folder as its a pre-requsite
create_logs_dir(){
  if ! ls $GRPL_WORKDIR | grep 'logs' >/dev/null 2>&1; then
    mkdir $GRPL_WORKDIR/logs 2>/dev/null | true
  fi
}

prompt_for_input_with_validation() {
    local prompt=$1
    local placeholder=$2
    local regex=$3
    local error_message=$4
    local default_value=$5  # Added parameter for default value
    local input=""

    while [[ ! $input =~ $regex ]]; do
        input=$(gum input --prompt "$prompt" --placeholder "$placeholder" --value "$default_value") || exit_on_interrupt
        if [[ ! $input =~ $regex ]]; then
            echo -e "${RED}$error_message${NC}" >&2
        fi
    done
    echo "$input"
}

install_prerequisite
create_logs_dir

