#!/bin/bash
set -e
export GRPL_WORKDIR=$(cd $(dirname $0) && pwd)
export FULL_COMMAND="$0 $@"
# shellcheck source=common
. "$GRPL_WORKDIR/common"

cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
the grapple cli
Version: $(cat $GRPL_WORKDIR/VERSION)
https://grapple-solutions.com/

Usage: $cli_name [command]

Commands:
  install    Installation
  cluster    Cluster commands
  example    example commands
  *          Help
"
  exit 0
}


# cli_log "Exporting config ..."
# [ ! -f "$GRPL_WORKDIR/config" ] \
#   && echo "ERROR: No $GRPL_WORKDIR/config file found. " \
#   && echo "cp $GRPL_WORKDIR/config.template $GRPL_WORKDIR/config and adjust." \
#   && exit 1

# export $(cat "$GRPL_WORKDIR/config" | xargs)

case "$1" in
  install|i)
    "$GRPL_WORKDIR/commands/install" $(echo $@ | sed 's,install,,g' | sed 's,i ,,') | tee -ia "$GRPL_WORKDIR/logs/install.log"
    ;;
  cluster|c)
    "$GRPL_WORKDIR/commands/cluster" $(echo $@ | sed 's,cluster,,g' | sed 's,c ,,') | tee -ia "$GRPL_WORKDIR/logs/cluster.log"
    ;;
  example|e)
    "$GRPL_WORKDIR/commands/example" $(echo $@ | sed 's,example,,g' | sed 's,e ,,') | tee -ia "$GRPL_WORKDIR/logs/example.log"
    ;;
  version|v)
    "$GRPL_WORKDIR/commands/version" $(echo $@ | sed 's,version,,g' | sed 's,v ,,') | tee -ia "$GRPL_WORKDIR/logs/version.log"
    ;;
  upgrade|u)
    "$GRPL_WORKDIR/commands/upgrade" $(echo $@ | sed 's,upgrade,,g' | sed 's,u ,,') | tee -ia "$GRPL_WORKDIR/logs/upgrade.log"
    ;;
  *)
    cli_help
    ;;
esac
