#!/bin/bash
set -e
export GRPL_WORKDIR=$(cd $(dirname $0) && pwd)
export FULL_COMMAND="$0 $@"

. "$GRPL_WORKDIR/utils/package_installer"
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_cli_help
  exit 0
}

# its a pre-requsite to create logs folder for log files
# since we don't want to import everything from common, so just 
# creating he here
if ! ls $GRPL_WORKDIR | grep 'logs' >/dev/null 2>&1; then
  mkdir $GRPL_WORKDIR/logs 2>/dev/null | true
fi


case "$1" in
  install|i)
    "$GRPL_WORKDIR/commands/install" $(echo $@ | sed 's,install,,g' | sed 's,i ,,') | tee -ia "$GRPL_WORKDIR/logs/install.log" >/dev/null
    ;;
  cluster|c)
    "$GRPL_WORKDIR/commands/cluster" $(echo $@ | sed 's,cluster,,g' | sed 's,c ,,') | tee -ia "$GRPL_WORKDIR/logs/cluster.log" >/dev/null
    ;;
  example|e)
    "$GRPL_WORKDIR/commands/example" $(echo $@ | sed 's,example,,g' | sed 's,e ,,') | tee -ia "$GRPL_WORKDIR/logs/example.log" >/dev/null
    ;;
  version|v)
    "$GRPL_WORKDIR/commands/version" $(echo $@ | sed 's,version,,g' | sed 's,v ,,') | tee -ia "$GRPL_WORKDIR/logs/version.log"
    ;;
  upgrade|u)
    "$GRPL_WORKDIR/commands/upgrade" $(echo $@ | sed 's,upgrade,,g' | sed 's,u ,,') | tee -ia "$GRPL_WORKDIR/logs/upgrade.log" >/dev/null
    ;;
  doc)
    generate_web_doc | tee -ia "$GRPL_WORKDIR/logs/doc.log" >/dev/null
    ;;
  *)
    cli_help
    ;;
esac
