#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
#   grpl_ai_cli_help
  status_log $TYPE_INFO "grpl ai cli help menu in development"
  exit 0
}

install_prerequisite

command=$1
shift
case "$command" in
  resource|r)
    "$GRPL_WORKDIR/commands/ai_commands/resource" $(echo $@) | tee -ia "$GRPL_WORKDIR/logs/ai_resource.log"
    ;;
  *)
    cli_help
    ;;
esac
