#!/bin/bash

set -e
set -o pipefail
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_application_cli_help
  exit 0
}

command=$1
shift
case "$command" in
  init|i)
    "$GRPL_WORKDIR/commands/application_commands/init" "$@" | tee -ia "$GRPL_WORKDIR/logs/app_init.log"
    ;;
  *)
    cli_help
    ;;
esac
