#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_application_cli_help
  exit 0
}

case "$1" in
  init|i)
    "$GRPL_WORKDIR/commands/aoo_commands/init" $(echo $@ | sed 's,init,,g' | sed 's,i ,,') | tee -ia "$GRPL_WORKDIR/logs/app_init.log"
    ;;
  *)
    cli_help
    ;;
esac
