#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_aws_cli_help
  exit 0
}


install_prerequisite
command=$1
shift
case "$command" in
  install|i)
    "$GRPL_WORKDIR/commands/aws_commands/install" $(echo $@) | tee -ia "$GRPL_WORKDIR/logs/aws_install.log"
    ;;
  install_deploy|id)
    "$GRPL_WORKDIR/commands/aws_commands/install_test" $(echo $@) | tee -ia "$GRPL_WORKDIR/logs/aws_install.log"
    ;;
  *)
    cli_help
    ;;
esac
