#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_cluster_cli_help
  exit 0
}

generate_web_doc() {
  grpl_cluster_cli_help "web-doc"
  exit 0
}

install_prerequisite
command=$1
shift
case "$command" in
  status|s)
    "$GRPL_WORKDIR/commands/cluster_commands/status" "$@" | tee -ia "$GRPL_WORKDIR/logs/cluster_status.log"
    ;;
  install|i)
    "$GRPL_WORKDIR/commands/cluster_commands/install" "$@" | tee -ia "$GRPL_WORKDIR/logs/cluster_install.log"
    ;;
  create|c)
    "$GRPL_WORKDIR/commands/cluster_commands/create" "$@" | tee -ia "$GRPL_WORKDIR/logs/cluster_create.log"
    ;;
  patch|p)
    "$GRPL_WORKDIR/commands/cluster_commands/patch" "$@" | tee -ia "$GRPL_WORKDIR/logs/cluster_patch.log"
    ;;
  connect|conn)
    "$GRPL_WORKDIR/commands/cluster_commands/connect" "$@" | tee -ia "$GRPL_WORKDIR/logs/cluster_connect.log"
    ;;
  *)
    cli_help
    ;;
esac
