#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/common"

cli_help() {
  cli_name=${0##*/}
  if ! grep -q "grpl" "$GRPL_WORKDIR/VERSION" >/dev/null 2>&1; then 
    extract_grapple_cli_version
  fi
  echo "
$cli_name
the grapple cli
Version: $(cat $GRPL_WORKDIR/VERSION)
https://grapple-solutions.com/

Usage: $cli_name [command]

Commands:
  status     Cluster status
  install    Cluster installation
  create     Cluster creation
  *          Help
" >&2
  exit 0
}

case "$1" in
  status|s)
    "$GRPL_WORKDIR/commands/cluster_commands/status" $(echo $@ | sed 's,status,,g' | sed 's,s ,,') | tee -ia "$GRPL_WORKDIR/logs/cluster_status.log"
    ;;
  install|i)
    "$GRPL_WORKDIR/commands/cluster_commands/install" $(echo $@ | sed 's,install,,g' | sed 's,i ,,') | tee -ia "$GRPL_WORKDIR/logs/cluster_install.log"
    ;;
  create|c)
    "$GRPL_WORKDIR/commands/cluster_commands/create" $(echo $@ | sed 's,create,,g' | sed 's,c ,,') | tee -ia "$GRPL_WORKDIR/logs/cluster_create.log"
    ;;
  *)
    cli_help
    ;;
esac
