#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/common"
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_dev_cli_help
  exit 0
}

[ "$1" = "help" ] || [ "$1" = "h" ] && cli_help

install_prerequisite
check_and_install_devspace

cli_args=$@

# devspace dev command
if [[ $# == 0 ]]; then
  devspace dev
  exit 0
fi

# devspace use namespace command
if [[ $1 == "ns" ]]; then
  shift
  cli_args=$@
  if [[ "$1" == "" ]]; then
    cli_args="--help"
  fi
  devspace use namespace $cli_args
  exit 0
fi

# devspace enter grapi/gruim command
if [[ $# == 2 ]] && [[ $1 == "enter" ]] && ( [[ $2 == "grapi" ]] || [[ $2 == "gruim" ]] ) ; then
  devspace enter  --label-selector app.kubernetes.io/name=$2
  exit 0
fi

devspace $cli_args


