#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/common"
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_dev_cli_help
  exit 0
}

[ "$1" = "help" ] || [ "$1" = "h" ] && cli_help

install_prerequisite
check_and_install_devspace

cli_args=$@

# TODO: please handle case, if file is not present
# 1) read from current folder?
# 2) store history of projects to be re-used?
# 3) ask for project name if new
# PROJECT_NAME=$(cat "/tmp/grpl_project_name.txt")
# I think cd is not necessary - let's assume we are in the correct folder
# verify, that we are in the right folder. we should know the structure
# responde with an error, if we are not in the right folder (if required for the command to run - for many comamnds that's not required)
#cd "$GRPL_WORKDIR/$PROJECT_NAME"

# devspace dev command
if [[ $# == 0 ]]; then
  devspace dev
  exit 0
fi

# devspace use namespace command
if [[ $1 == "ns" ]]; then
  shift
  cli_args=$@
  if [[ "$1" == "" ]]; then
    cli_args="--help"
  fi
  devspace use namespace $cli_args
  exit 0
fi

# devspace enter grapi/gruim command
if [[ $# == 2 ]] && [[ $1 == "enter" ]] && ( [[ $2 == "grapi" ]] || [[ $2 == "gruim" ]] ) ; then
  echo "here"
  devspace enter  --label-selector app.kubernetes.io/name=$2
fi

devspace $cli_args


