#!/bin/bash
set -e
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_cluster_status_cli_help
  exit 0
}

[ "$1" = "help" ] || [ "$1" = "h" ] && cli_help
[ "$1" = "cli" ] && generate_cli_web_doc
[ "$1" = "gras" ] && generate_gras_web_doc

