#!/bin/bash
set -e
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_web_doc_cli_help
  exit 0
}


[ "$1" = "help" ] || [ "$1" = "h" ] && cli_help && exit 0

install_prerequisite
check_and_install_asciidoc

[ "$1" = "cli" ] && generate_cli_web_doc && exit 0
[ "$1" = "crds" ] && generate_crds_web_doc && exit 0

status_log $TYPE_ERROR "Error: Invalid resource '$1' specified"
exit 1
