#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/common"

cli_help() {
  cli_name=${0##*/}
  if ! grep -q "grpl" "$GRPL_WORKDIR/VERSION" >/dev/null 2>&1; then 
    extract_grapple_cli_version
  fi
  echo "
$cli_name
the grapple cli
Version: $(cat $GRPL_WORKDIR/VERSION)
https://grapple-solutions.com/

Usage: $cli_name [command]

Commands:
  status    status of example
  deploy    deploy an example
  *         Help
" >&2
  exit 0
}

case "$1" in
  status|s)
    "$GRPL_WORKDIR/commands/example_commands/status" $(echo $@ | sed 's,status,,g' | sed 's,s ,,') | tee -ia "$GRPL_WORKDIR/logs/example_status.log"
    ;;
  deploy|d)
    "$GRPL_WORKDIR/commands/example_commands/deploy" $(echo $@ | sed 's,deploy,,g' | sed 's,i ,,') | tee -ia "$GRPL_WORKDIR/logs/example_deploy.log"
    ;;
  *)
    cli_help
    ;;
esac
