#!/bin/bash
set -e
. "$GRPL_WORKDIR/utils/common"

cli_help_install() {
  echo "
Command: install

Usage: 
  install tool_name" >&2
  exit 0
}

[ "$1" = "help" ] || [ "$1" = "h" ] && cli_help_install


cli_log "install BEGIN"



cli_log "install END"
