#!/bin/bash


set -e
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_k3d_cli_help
  exit 0
}

install_prerequisite
check_and_install_k3d

command=$1
shift

case "$command" in
  create|c)
    "$GRPL_WORKDIR/commands/k3d_commands/create" "$@" | tee -ia "$GRPL_WORKDIR/logs/k3d_create.log"
    ;;
  install|i)
    "$GRPL_WORKDIR/commands/k3d_commands/install" "$@" | tee -ia "$GRPL_WORKDIR/logs/k3d_install.log"
    ;;
  patch_dns|pd)
    "$GRPL_WORKDIR/commands/k3d_commands/patch_dns" "$@" | tee -ia "$GRPL_WORKDIR/logs/k3d_patch_dns.log"
    ;;
  *)
    cli_help
    ;;
esac
