#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_resource_cli_help
  exit 0
}

command=$1
shift
case "$command" in
  deploy|d)
    "$GRPL_WORKDIR/commands/resource_commands/deploy" $(echo $@) | tee -ia "$GRPL_WORKDIR/logs/resource_deploy.log"
    ;;
  render|r)
    "$GRPL_WORKDIR/commands/resource_commands/render" $(echo $@) | tee -ia "$GRPL_WORKDIR/logs/resource_render.log"
    ;;
  *)
    cli_help
    ;;
esac
