#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/common"

cli_upgrade_help() {
  cli_name=${0##*/}
  if ! grep -q "grpl" "$GRPL_WORKDIR/VERSION" >/dev/null 2>&1; then 
    extract_grapple_cli_version
  fi
  echo "
$cli_name
the grapple cli
Version: $(cat $GRPL_WORKDIR/VERSION)
https://grapple-solutions.com/

Usage: $cli_name [command]

Commands:
  *         Help
" >&2
  exit 0
}

[ "$1" = "help" ] || [ "$1" = "h" ] && cli_upgrade_help

echo "run upgrade"