#!/bin/bash

set -e
. "$GRPL_WORKDIR/utils/common"

cli_version_help() {
  cli_name=${0##*/}
  echo "
$cli_name
the grapple cli
Version: $(cat $GRPL_WORKDIR/VERSION)
https://grapple-solutions.com/

Usage: $cli_name [command]

Commands:
  *         Help
"
  exit 0
}

[ "$1" = "help" ] || [ "$1" = "h" ] && cli_version_help

  current="$(cat $GRPL_WORKDIR/VERSION)"
  new=$(brew outdated --json grapple-cli 2>/dev/null | grep -o '"current_version": "[^"]*"' | sed 's/"current_version": "//;s/"$//')
if [[ "$new" != "" && "$current" != "$new" ]]; then
  echo "
New version $new is available, run 'grpl upgrade' to upgrade to new version"
fi
  echo "
version
the grapple cli
Version: $(cat $GRPL_WORKDIR/VERSION)
"
if ls $GRPL_WORKDIR | grep 'dependency_versions' >/dev/null 2>&1; then
  echo "$(cat $GRPL_WORKDIR/dependency_versions)"
fi
echo "
https://grapple-solutions.com/
"



