#!/bin/bash

set -e
. "$GRPL_WORKDIR/common"

cli_version_help() {
  cli_name=${0##*/}
  echo "
$cli_name
the grapple cli
Version: $(cat $GRPL_WORKDIR/VERSION)
https://grapple-solutions.com/

Usage: $cli_name [command]

Commands:
  *         Help
"
  exit 1
}

[ "$1" = "help" ] || [ "$1" = "h" ] && cli_version_help

cat $GRPL_WORKDIR/VERSION
