apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: function-example
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
  - step: run-the-template
    functionRef:
      name: function-example
    input:
      apiVersion: template.fn.crossplane.io/v1beta1
      kind: Input
      email: "zahid.iqbal.marth.1998@gmail.com"
