#!/bin/bash
set -e
. "$GRPL_WORKDIR/utils/common"
. "$GRPL_WORKDIR/utils/checks"
. "$GRPL_WORKDIR/utils/help_menus"


cli_help() {
  grpl_license_remove_cli_help
  exit 0
}

[ "$1" = "help" ] || [ "$1" = "h" ] && cli_help


if ! kubectl patch secret grsf-config -n grpl-system --type='json' -p="[{\"op\": \"remove\", \"path\": \"/data/LIC\"}]" >/dev/null 2>&1; then
    status_log $TYPE_ERROR "Failed to remove License (LIC) from grsf-config secret becuase it does not exist"
    exit 1
fi

status_log $TYPE_SUCCESS "LIC (License) removed successfully"