

kube-prometheus:
  enabled: false
  # serviceAccount:
  #   create: true
  #   name: "amp-iamproxy-ingest-service-account"
  #   annotations:
  #       eks.amazonaws.com/role-arn: "arn:aws:iam::046690449381:role/amp-iamproxy-ingest-role"
  # prometheus:
  #   enabled: false
  #   remoteWriteDashboards: true
  #   remoteWrite:
  #       - url: https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-9f2d668b-1fd6-473d-892f-9c442d346cf8/api/v1/remote_write
  #         # sigv4: # does not work with kube-prometheus
  #         #   region: eu-central-1
  #         # queue_config: # does not work with kube-prometheus
  #         #   max_samples_per_send: 1000
  #         #   max_shards: 200
  #         #   capacity: 2500


kube-prometheus-stack:
  enabled: true
  prometheus:
    prometheusSpec:  
      remoteWriteDashboards: true
      remoteWrite:
          - url: https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-9f2d668b-1fd6-473d-892f-9c442d346cf8/api/v1/remote_write
            sigv4:
              region: eu-central-1
            # queue_config:
            #   max_samples_per_send: 1000
            #   max_shards: 200
            #   capacity: 2500
      # additionalScrapeConfigs:
      # - job_name: kube-etcd
      # ...
      # serviceMonitorSelector:
      #   matchLabels:
      #     app.kubernetes.io/instance: grsf-monitoring
      #     app.kubernetes.io/name: prometheus-node-exporter
      # serviceMonitorNamespaceSelector:
      #   matchLabels:
      #     name: grsf-monitoring
      # ruleSelectorNilUsesHelmValues: false
      # serviceMonitorSelectorNilUsesHelmValues: false
      # podMonitorSelectorNilUsesHelmValues: false
      # probeSelectorNilUsesHelmValues: false
    additionalServiceMonitors:
      - name: grapi-metrics
        selector:
          matchLabels:
            app.kubernetes.io/name: grapi
        namespaceSelector:
          any: true
          # matchNames:
          # - grpl-test
          # - jcs-test
        endpoints:
          - port: metrics
      - name: gruim-metrics
        selector:
          matchLabels:
            app.kubernetes.io/name: gruim
        namespaceSelector:
          any: true
          # matchNames:
          # - grpl-test
          # - jcs-test
        endpoints:
          - port: metrics

    serviceAccounts:
        name: "amp-iamproxy-ingest-service-account"
        annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::046690449381:role/amp-iamproxy-ingest-role"


# prometheus:
#   enabled: true
#   serviceAccounts:
#       server:
#           name: "amp-iamproxy-ingest-service-account"
#           annotations:
#               eks.amazonaws.com/role-arn: "arn:aws:iam::046690449381:role/amp-iamproxy-ingest-role"
#   server:
#     persistentVolume:
#       enabled: false
#     remoteWriteDashboards: true
#     remoteWrite:
#         - url: https://aps-workspaces.eu-central-1.amazonaws.com/workspaces/ws-9f2d668b-1fd6-473d-892f-9c442d346cf8/api/v1/remote_write
#           sigv4:
#             region: eu-central-1
#           queue_config:
#             max_samples_per_send: 1000
#             max_shards: 200
#             capacity: 2500