#!/bin/bash

# target plateforms
CIVO="CIVO"
Kubernetes="Kubernetes"
Minikube="minikube"

# Status Types
TYPE_SUCCESS='SUCCESS'
TYPE_INFO='INFO'
TYPE_ERROR='ERROR'
TYPE_DEFAULT='DEFAULT'
# Status Type Colors
success_color="\033[1;32m"  # Green color
info_color="\033[1;33m"  # Blue color
error_color="\033[1;31m"  # Red color
reset_color="\033[0m"    # Reset color


# list of regexes used for validation
ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"
email_regex="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
dns_regex="^[A-Za-z0-9]([-A-Za-z0-9]*[A-Za-z0-9])?(\.[A-Za-z0-9]([-A-Za-z0-9]*[A-Za-z0-9])?)*\.[A-Za-z]{2,}$"
grpl_dns_regex="^[[:alnum:]-]{3,}$"
non_empty_regex=".+" 
alphaNum_plus_hyphen_and_underscope_regex="^[a-zA-Z0-9_-]+$"
url_validation_regex="^(http(s)?:\/\/)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)$"
abs_path_regex="^(.+)\/([^\/]+)$"
# exist on interupt message colors
RED='\033[0;31m'
NC='\033[0m' # No Color

# input params type
cli_params="--params"
config_file_params="--configfile"

# help menu types
WEB_DOC="web-doc"

# gras templates
DB_FILE="db-file"
DB_MYSQL="db-mysql"
DB_MYSQL_DISCOVERY_BASED="db-mysql-discovery-based"
DB_POSTGRES="db-postgres"
DB_POSTGRES_DISCOVERY_BASED="db-postgres-discovery-based"

#db type
INTERNAL_DB="internal"
EXTERNAL_DB="external"


GRUIM="
gruim:
  # uiimagetag: "0.1.38"
  ssl: true
  sslissuer: letsencrypt-grapple-demo
  style: '{\"colors\":{\"primary\":{\"DEFAULT\":\"#34344A\",\"fg\":\"#fff\"},\"accent\":{\"DEFAULT\":\"#CC5A71\",\"fg\":\"#fff\"}}}'
  config: \"\"
  additionalpackages: \"\"
"


  #relations
  BELONGS_TO="belogsTo"
  HAS_MANY="hasMany"
  HAS_MANY_THROUGH="hasManyThrough"
  HAS_ONE="hasOne"
  REFRENCES_MANY="refrencesMany"
