#!/bin/bash

# target plateforms
CIVO="CIVO"
Kubernetes="Kubernetes"
Minikube="minikube"

# Status Types
TYPE_SUCCESS='SUCCESS'
TYPE_INFO='INFO'
TYPE_ERROR='ERROR'
TYPE_DEFAULT='DEFAULT'
# Status Type Colors
success_color="\033[1;32m"  # Green color
info_color="\033[1;33m"  # Blue color
error_color="\033[1;31m"  # Red color
reset_color="\033[0m"    # Reset color


# list of regexes used for validation
ip_regex="^([0-9]{1,3}\.){3}[0-9]{1,3}$"
email_regex="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
dns_regex="^[A-Za-z0-9]([-A-Za-z0-9]*[A-Za-z0-9])?(\.[A-Za-z0-9]([-A-Za-z0-9]*[A-Za-z0-9])?)*\.[A-Za-z]{2,}$"
grpl_dns_regex="^[[:alnum:]-]{3,}$"
non_empty_regex=".+" 
alphaNum_plus_hyphen_and_underscope_regex="^[a-zA-Z0-9_-]+$"

# exist on interupt message colors
RED='\033[0;31m'
NC='\033[0m' # No Color

# input params type
cli_params="--params"
config_file_params="--configfile"

# help menu types
WEB_DOC="web-doc"