#!/bin/bash


# available packages installations
# package names
# helm
# kubectl
# gum="minikube"
# civo
# kbcli
# kubeblocks
# yq


check_and_install_snap() {

    # if OS is gnu, we want to check and install snap
    # this package will be used to install other packages in future
    if [ $OS == "gnu" ] && ! snap version >/dev/null 2>&1; then
        echo "snap is a prerequisite package manager to install packages for linux"
        echo "installing snap..."
        sudo apt update
        sudo apt install snapd
        snap --version | grep snapd >> "$GRPL_WORKDIR/dependency_versions"
    fi

}

check_and_install_gum() {

    # checks for checking and installing gum
    if ! gum --version >/dev/null 2>&1; then
            echo "gum is a prerequisite for this script to run."
            echo "installing gum..."
        if [ "${OS}" == "mac" ]; then
            brew install gum
        elif [ "${OS}" == "gnu" ]; then 
            sudo mkdir -p /etc/apt/keyrings
            curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
            echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
            sudo apt update && sudo apt install gum
            sudo ln -s /usr/bin/gum /snap/bin/gum
        else
            errMsg="Failed to install a prerequisite gum, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_gum_cli_version

}

check_and_install_helm() {

    # checks for checking and installing helm
    if ! helm >/dev/null 2>&1; then
        echo "helm is a prerequisite for this script to run."
        echo "installing helm..."
        if [ $OS == "mac" ]; then 
            eval "$(getGumSpinnerOrLogger "a prerequisite helm is not installed, now installing helm") brew install helm"
        elif [ $OS == "gnu" ]; then
            sudo snap refresh >/dev/null 2>&1
            eval "$(getGumSpinnerOrLogger "a prerequisite helm is not installed, now installing helm") sudo snap install helm --classic"
        else
            errMsg="Failed to install a prerequisite helm, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_helm_cli_version

}

check_and_install_kubectl(){

    # checks for checking and installing kubectl
    if ! kubectl >/dev/null 2>&1; then
        echo "kubectl is a prerequisite for this script to run."
        echo "installing kubectl..."
        if [ $OS == "mac" ]; then 
            eval "$(getGumSpinnerOrLogger "a prerequisite kubectl is not installed, now installing kubectl") brew install kubectl"
        elif [ $OS == "gnu" ]; then
            sudo snap refresh >/dev/null 2>&1
            eval "$(getGumSpinnerOrLogger "a prerequisite kubectl is not installed, now installing kubectl") sudo snap install kubectl --classic"
        else
            errMsg="Failed to install a prerequisite kubectl, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

}

check_and_install_civo() {

    # checks for checking and installing civo
    if ! civo version 2>&1; then
        echo "civo cli is required"
        echo "installing civo cli..."
        if [ $OS == "mac" ]; then 
            eval "$(getGumSpinnerOrLogger "a prerequisite civo is not installed, now tapping civo") brew tap civo/tools"
            eval "$(getGumSpinnerOrLogger "a prerequisite civo is not installed, now installing civo") brew install civo"
        elif [ $OS == "gnu" ]; then
            eval "$(getGumSpinnerOrLogger "a prerequisite civo is not installed, now installing civo") curl -sL https://civo.com/get | sh"
            status_log $TYPE_INFO "going to move /tmp/civo /usr/local/bin/civo this might take some time"
            sudo mv /tmp/civo /usr/local/bin/civo
        else
            errMsg="Failed to install a prerequisite helm, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi
 
    extract_civo_cli_version
}

check_and_install_minikube() {

    # checks for checking and installing minikube
    if ! minikube version 2>&1; then
        echo "minikube cli is required"
        echo "installing minikube cli..."
        if [ "${OS}" == "mac" ]; then
            eval "$(getGumSpinnerOrLogger "a prerequisite minikube is not installed, now installing minikube") brew install minikube"
        elif [ "${OS}" == "gnu" ]; then
            eval "$(getGumSpinnerOrLogger "a prerequisite minikube is not installed, now installing minikube") wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64"
            chmod +x minikube-linux-amd64
            sudo mv minikube-linux-amd64 /usr/local/bin/minikube
        else
            errMsg="Failed to install minikube, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_minikube_cli_version

}

check_and_install_kbcli() {

    # checks for checking and installing kbcli
    if ! kbcli >/dev/null 2>&1; then
        echo "kbcli cli is required"
        echo "installing kbcli cli..."
        if [ "${OS}" == "mac" ] || [ "${OS}" == "gnu" ]; then
            eval "$(getGumSpinnerOrLogger "a prerequisite kbcli is not installed, now installing kbcli") curl -fsSL https://kubeblocks.io/installer/install_cli.sh | bash "
        else
            errMsg="Failed to install kbcli, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi
       
    extract_kbcli_cli_version

}

check_and_install_kubeblocks() {

    # checks for checking and installing kubeblocks
    if ! kbcli cluster list 2>/dev/null || ! kbcli kubeblocks status; then
        eval "$(getGumSpinnerOrLogger "installing kubeblocks") kbcli kubeblocks install --set image.registry=\"docker.io\""
    fi
   
    extract_kubeblocks_cli_version
    
}

check_and_install_asciidoc() {

    # checks for checking and installing minikube
    if ! asciidoctor --version  >/dev/null 2>&1; then
        echo "asciidoctor cli is required"
        echo "installing asciidoctor cli..."
        if [ "${OS}" == "mac" ]; then
            eval "$(getGumSpinnerOrLogger "asciidoctor is not installed, now installing asciidoctor") brew install asciidoctor"
        elif [ "${OS}" == "gnu" ]; then
            status_log $TYPE_INFO "going to refresh snap"
            sudo snap refresh 2>&1
            eval "$(getGumSpinnerOrLogger "ruby is not installed, now installing ruby") sudo snap install ruby --classic"
            eval "$(getGumSpinnerOrLogger "asciidoctor is not installed, now installing asciidoctor") gem install asciidoctor"
            exe_file_path=$(gem which asciidoctor)
            extracted_version=$(echo "$exe_file_path" | awk -F '/' '{print $6}')
            asciidoc_template_path="~/.gem/gems/{}/bin"
            asciidoc_path=$(echo "$asciidoc_template_path" | sed 's/{}/asciidoctor-2.0.23/')
            export PATH="$asciidoc_path:$PATH"
            echo "$asciidoc_path:$PATH"
        else
            errMsg="Failed to install asciidoctor, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

}

check_and_install_git() {

    # checks for checking and installing git
    if ! git version  >/dev/null 2>&1; then
        echo "git cli is required"
        echo "installing git cli..."
        if [ "${OS}" == "mac" ]; then
            eval "$(getGumSpinnerOrLogger "git is not installed, now installing git") brew install git"
        elif [ "${OS}" == "gnu" ]; then
            status_log $TYPE_INFO "going to update apt"
            sudo apt update 2>&1
            eval "$(getGumSpinnerOrLogger "git is not installed, now installing git") sudo apt install git"
        else
            errMsg="Failed to install git, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_git_cli_version
    
}

check_and_install_gh() {

    # checks for checking and installing gh
    if ! gh --version  >/dev/null 2>&1; then
        echo "gh cli is required"
        echo "installing gh cli..."
        if [ "${OS}" == "mac" ]; then
            eval "$(getGumSpinnerOrLogger "gh is not installed, now installing gh") brew install gh"
        elif [ "${OS}" == "gnu" ]; then
            status_log $TYPE_INFO "going to update apt"
            sudo apt update 2>&1
            eval "$(getGumSpinnerOrLogger "gh is not installed, now installing gh") sudo apt-get install gh"
        else
            errMsg="Failed to install gh, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_gh_cli_version
    
}

check_and_install_yq() {

    # checks for checking and installing yq
    if ! yq --version  >/dev/null 2>&1; then
        echo "yq cli is required"
        echo "installing yq cli..."
        if [ "${OS}" == "mac" ]; then
            eval "$(getGumSpinnerOrLogger "yq is not installed, now installing yq") brew install yq"
        elif [ "${OS}" == "gnu" ]; then
            status_log $TYPE_INFO "going to refresh snap"
            sudo snap refresh >/dev/null 2>&1
            eval "$(getGumSpinnerOrLogger "yq is not installed, now installing yq") sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq"
        else
            errMsg="Failed to install yq, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_yq_cli_version
    
}

check_and_install_gettext() {

    if [ "${OS}" != "mac" ]; then
        return 0
    fi
    # checks for checking and installing git
    if ! gettext --version  >/dev/null 2>&1; then
        echo "gettext cli is required"
        echo "installing gettext cli..."
        eval "$(getGumSpinnerOrLogger "gettext is not installed, now installing gettext") brew install gettext"
        eval "$(getGumSpinnerOrLogger "linking gettext") brew link --force gettext"
    fi
    
}


check_and_install_jq() {

    # checks for checking and installing jq
    if ! jq --version  >/dev/null 2>&1; then
        echo "jq cli is required"
        echo "installing jq cli..."
        if [ "${OS}" == "mac" ]; then
            eval "$(getGumSpinnerOrLogger "jq is not installed, now installing jq") brew install jq"
        elif [ "${OS}" == "gnu" ]; then
            status_log $TYPE_INFO "going to refresh snap"
            sudo snap refresh >/dev/null 2>&1
            eval "$(getGumSpinnerOrLogger "jq is not installed, now installing jq") sudo wget https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 && sudo chmod +x jq-linux64 && sudo mv jq-linux64 /usr/local/bin/jq"
        else
            errMsg="Failed to install jq, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_jq_cli_version
    
}


check_and_install_devspace() {

    # checks for checking and installing devspace
    if ! devspace --version  >/dev/null 2>&1; then
        echo "devspace cli is required"
        echo "installing devspace cli..."
        if [ "${OS}" == "mac" ]; then
            eval "$(getGumSpinnerOrLogger "devspace is not installed, now installing devspace") brew install devspace"
        elif [ "${OS}" == "gnu" ]; then
            status_log $TYPE_INFO "going to refresh snap"
            sudo snap refresh >/dev/null 2>&1
            eval "$(getGumSpinnerOrLogger "devspace is not installed, now installing devspace") curl -L -o devspace "https://github.com/loft-sh/devspace/releases/latest/download/devspace-linux-amd64" && sudo install -c -m 0755 devspace /usr/local/bin"
        else
            errMsg="Failed to install devspace, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_devspace_cli_version
    
}


check_and_install_glow() {

    # checks for checking and installing glow cli
    if ! glow --version  >/dev/null 2>&1; then
        echo "glow cli is required"
        echo "installing glow cli..."
        if [ "${OS}" == "mac" ]; then
            eval "$(getGumSpinnerOrLogger "glow cli is not installed, now installing glow cli") brew install glow"
        elif [ "${OS}" == "gnu" ]; then
            status_log $TYPE_INFO "going to refresh snap"
            sudo snap refresh >/dev/null 2>&1
            eval "$(getGumSpinnerOrLogger "glow cli is not installed, now installing glow cli") sudo snap install glow"
        else
            errMsg="Failed to install glow cli, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_glow_cli_version
    
}


check_and_install_taskcli() {

    # checks for checking and installing task cli
    if ! task --version  >/dev/null 2>&1; then
        echo "task cli is required"
        echo "installing task cli..."
        if [ "${OS}" == "mac" ]; then
            eval "$(getGumSpinnerOrLogger "task cli is not installed, now installing task cli") brew install go-task/tap/go-task"
        elif [ "${OS}" == "gnu" ]; then
            status_log $TYPE_INFO "going to refresh snap"
            sudo snap refresh >/dev/null 2>&1
            eval "$(getGumSpinnerOrLogger "task cli is not installed, now installing task cli") sudo snap install task --classic"
        else
            errMsg="Failed to install task cli, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_task_cli_version
    
}


check_and_install_aws_cli() {

    # checks for checking and installing aws cli
    if ! aws --version  >/dev/null 2>&1; then
        echo "aws cli is required"
        echo "installing aws cli..."
        if [ "${OS}" == "mac" ]; then
            eval "$(getGumSpinnerOrLogger "aws cli is not installed, now installing aws cli, this may take a while") brew install awscli"
        elif [ "${OS}" == "gnu" ]; then
            eval "$(getGumSpinnerOrLogger "aws cli is not installed, now installing aws cli, this may take a while") sudo apt-get update && sudo apt-get install -y unzip && curl 'https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip' -o 'awscliv2.zip' && unzip -q awscliv2.zip && sudo ./aws/install && echo 'export PATH=/usr/local/bin:$PATH' >> ~/.bashrc && source ~/.bashrc && rm -rf aws awscliv2.zip"
        else
            errMsg="Failed to install aws cli, OS ${OS} not supported at the moment"
            echo $errMsg
            status_log $TYPE_ERROR $errMsg
            exit 1
        fi
    fi

    extract_aws_cli_version

}


extract_helm_cli_version(){

    if ! grep -q "helm" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Store the output of 'helm version' in a variable
        helm_output=$(helm version 2>/dev/null)

        # Extract the Helm version number using sed and store it in a variable
        helm_version=$(echo "$helm_output" | sed -n 's/version.BuildInfo{Version:"\([^"]*\).*/\1/p')

        # Output the latest version
        echo "      $helm_version - helm" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}

extract_kubectl_cli_version(){

    if ! grep -q "kubectl" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Store the output of 'kubectl version' in a variable
        kubectl_output=$(kubectl version 2>/dev/null)

        # Extract the client version number using awk and store it in a variable
        kubectl_client_version=$(echo "$kubectl_output" | awk '/Client Version:/{print $NF}')

        # Output the latest version
        echo "      $kubectl_client_version - kubectl" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}


extract_gum_cli_version(){

    if ! grep -q "gum" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Store the output of 'gum -v' in a variable
        gum_output=$(gum -v 2>/dev/null)

        # Extract version number using grep
        gum_version=$(echo "$gum_output" | grep -o '[0-9][0-9.]*')

        # Output the latest version
        echo "      v$gum_version - gum" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}

extract_civo_cli_version(){

    if ! grep -q "civo" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Store the output of civo version in a variable
        civo_output=$(civo version 2>/dev/null)

        # Extract version number using grep and awk
        civo_version=$(echo "$civo_output" | grep -o 'Civo CLI v[0-9.]*' | awk '{print $3}')

        # Output the latest version
        echo "      $civo_version - civo" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}


extract_minikube_cli_version(){

    if ! grep -q "minikube" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Run minikube version command and capture its output
        minikube_output=$(minikube version 2>/dev/null)

        # Extract version number using grep and awk
        minikube_version=$(echo "$minikube_output" | grep -o 'minikube version: v[0-9.]*' | awk '{print $3}')

        # Output the latest version
        echo "      $minikube_version - minikube" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}


extract_kbcli_cli_version(){

    if ! grep -q "kbcli" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Run kbcli version command and capture its output
        kbcli_output=$(kbcli version 2>/dev/null)

        # Extract version number using grep and awk
        kbcli_version=$(echo "$kbcli_output" | grep -o 'kbcli: [0-9.]*' | awk '{print $2}')

        # Output the latest version
        echo "      v$kbcli_version - kbcli" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}

extract_kubeblocks_cli_version(){

    if ! grep -q "kubeblocks" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Run kbcli version command and capture its output
        output=$(kbcli version 2>/dev/null)

        # Extract KubeBlocks version number using grep and awk
        kubeblocks_version=$(echo "$output" | grep -o 'KubeBlocks: [0-9.]*' | awk '{print $2}')

        # Output the latest version
        echo "      v$kubeblocks_version - kubeblocks" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}

extract_grapple_cli_version(){

    if ! grep -q "." "$GRPL_WORKDIR/VERSION" >/dev/null 2>&1; then 

        # Extract grpl-cli version number
        grpl_version=$(brew list --versions grapple-cli | grep grapple-cli | awk '{print $2}')
        # Output the latest version
        echo "$grpl_version" > "$GRPL_WORKDIR/VERSION"
    fi

}


extract_git_cli_version(){

    if ! grep -q "git" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Run git version command and store the output
        git_version=$(git version)

        # Extract version number using regular expression
        regex="git version ([0-9]+\.[0-9]+\.[0-9]+)"
        version_number=""
        if [[ $git_version =~ $regex ]]; then
            version_number=${BASH_REMATCH[1]}
            echo "Git version number: $version_number"
        else
            echo "Failed to extract version number from git version output."
            return 0
        fi

        # Output the latest version
        echo "      v$version_number - git" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}

extract_gh_cli_version(){

    if ! grep -q "gh" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Run gh version command and store the output
        gh_version=$(gh --version)

        # Extract version number using regular expression
        regex="gh version ([0-9]+\.[0-9]+\.[0-9]+)"
        version_number=""
        if [[ $gh_version =~ $regex ]]; then
            version_number=${BASH_REMATCH[1]}
            echo "gh version number: $version_number"
        else
            echo "Failed to extract version number from gh version output."
            return 0
        fi

        # Output the latest version
        echo "      v$version_number - git" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}

extract_jq_cli_version(){

    if ! grep -q "jq" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Get jq version
        jq_version=$(jq --version | awk -F'[- ]' '{print $2}')

        # Output the latest version
        echo "      v$jq_version - jq" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}



extract_yq_cli_version(){

    if ! grep -q "yq" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Get yq version
        yq_version=$(yq --version | awk '{print $NF}')

        # Output the latest version
        echo "      $yq_version - yq" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}

extract_devspace_cli_version(){

    if ! grep -q "devspace" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Get yq version
        devspace_version=$(devspace version | awk -F ': ' '/DevSpace version/{print $2}')

        # Output the latest version
        echo "      $devspace_version - devspace" >> "$GRPL_WORKDIR/dependency_versions"
    fi

}


extract_task_cli_version(){

    if ! grep -q "task" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Get yq version
        task_version=$(task --version | awk '{print $3}')

        # Output the latest version
        echo "      $task_version - task" >> "$GRPL_WORKDIR/dependency_versions"
    fi
}


extract_glow_cli_version(){

    if ! grep -q "glow" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Get yq version
        glow_version=$(glow --version | awk '{print $3}')

        # Output the latest version
        echo "      $glow_version - glow" >> "$GRPL_WORKDIR/dependency_versions"
    fi
}


extract_aws_cli_version(){

    if ! grep -q "aws" "$GRPL_WORKDIR/dependency_versions" >/dev/null 2>&1; then 

        # Get yq version
        aws_version=$(aws --version | awk '{print $1}' | awk -F'/' '{print $2}')
        # Output the latest version
        echo "      $aws_version - aws" >> "$GRPL_WORKDIR/dependency_versions"
    fi
}