#!/bin/bash
set -e
. "$GRPL_WORKDIR/utils/help_menus"
. "$GRPL_WORKDIR/utils/checks"

cli_help() {
  grpl_resource_deploy_cli_help
  exit 0
}

[ "$1" = "help" ] || [ "$1" = "h" ] && cli_help

install_prerequisite
check_and_install_yq
check_and_install_jq

NS=grpl-system
DB_FILE_NS=grpl-dbfile
DB_NS=grpl-db
awsregistry="p7h7z5g3"
tmp_file_dest="/tmp/temp_file"




# ----------------------- functions code ---------------------------

transform_model_input_to_yaml() {

    local Models=$1
    # Convert the JSON-like string to valid JSON by replacing single quotes with double quotes
    json_string="${Models//\'/\"}"

    # Initialize an array to store the models
    models_name=()
    # Split the input string by pipe symbol (|)
    IFS='|' read -ra models_data <<< "$json_string"

    # Iterate over each model data
    index=0
    for model_data in "${models_data[@]}"; do
        # Extract the model name and its properties
        IFS=':' read -r model_name properties <<< "$model_data"
        yq -i ".grapi.models[$index].name=\"$model_name\" | .grapi.models[$index].name style=\"double\"" $template_file_dest
        
        # Parse the properties JSON and format it as YAML
        yq eval ".grapi.models[$index].spec += $properties" -i $template_file_dest
        models_name+=("$model_name")
        ((index+=1))
    done

}

transform_datasources_input_to_yaml() {

    local ds=$1
    # Convert the JSON-like string to valid JSON by replacing single quotes with double quotes
    json_string="${ds//\'/\"}"

    # Split the input string by pipe symbol (|)
    IFS='|' read -ra data_sources <<< "$json_string"

    # Iterate over each model data
    index=0
    for data_source in "${data_sources[@]}"; do
        # Extract the model name and its properties
        IFS=':' read -r data_source_name properties <<< "$data_source"
        yq -i ".grapi.datasources[$index].name=\"$data_source_name\" | .grapi.datasources[$index].name style=\"double\"" $template_file_dest
        
        connector=$(echo $properties | jq -r '.connector')
        DATABASE_SCHEMA=$(echo $properties | jq -r '.database')
        host=$(echo $properties | jq -r '.host')
        port=$(echo $properties | jq -r '.port')
        user=$(echo $properties | jq -r '.user')
        password=$(echo $properties | jq -r '.password')
        url=$(echo $properties | jq -r '.url')

        # Parse the properties JSON and format it as YAML
        # yq eval ".grapi.datasources[$index].spec.$connector += $properties" -i $template_file_dest
        ((index+=1))
    done

}

transform_discoveries_input_to_yaml() {
    

    local dsq=$1
    # Convert the JSON-like string to valid JSON by replacing single quotes with double quotes
    json_string="${dsq//\'/\"}"

    # Split the input string by pipe symbol (|)
    IFS='|' read -ra discoveries <<< "$json_string"

    # Iterate over each model data
    index=0
    for discovery in "${discoveries[@]}"; do
        # Extract the model name and its properties
        IFS=':' read -r discovery_name properties <<< "$discovery"
        yq -i ".grapi.discoveries[$index].name=\"$discovery_name\" | .grapi.discoveries[$index].name style=\"double\"" $template_file_dest

        if [[ "$DATABASE_SCHEMA" == "" ]]; then
            DATABASE_SCHEMA=$(echo $properties | jq -r '.schema')
        fi
        
        # Parse the properties JSON and format it as YAML
        yq eval ".grapi.discoveries[$index].spec += $properties" -i $template_file_dest
        ((index+=1))
    done

}


take_relation_input_from_cli() {
   
    status_log $TYPE_INFO "Do you want to add a relationship?"
    local another_rule=$(gum choose "Yes" "No") || exit $?
    
    if [ "$another_rule" == "No" ]; then
        return 0
    fi
    
    local models=("$@")
    local models_len=${#models[@]}
    index=0


    while true; do

        local relation_type=$(gum choose --header "Please select the relation type" $BELONGS_TO $HAS_MANY $HAS_MANY_THROUGH $HAS_ONE $REFRENCES_MANY) || exit $?
        status_log $TYPE_DEFAULT  "relation model template: ${relation_type}"

        if [[ $models_len > 0 ]]; then 
            local source_model=$(gum choose --header "Please select source model" "${models[@]}") || exit $?
            status_log $TYPE_DEFAULT  "source model: ${source_model}"

            local target_model=$(gum choose --header "Please select target model" "${models[@]}") || exit $?
            status_log $TYPE_DEFAULT  "destination model: ${target_model}" 
        else
            local source_model=$(prompt_for_input_with_validation "Please enter source model: " "source model" "$non_empty_regex" "please enter a valid value") || exit $?
            status_log $TYPE_DEFAULT  "source model: ${source_model}"

            local target_model=$(prompt_for_input_with_validation "Please enter target model: " "target model" "$non_empty_regex" "please enter a valid value") || exit $?
            status_log $TYPE_DEFAULT  "destination model: ${target_model}"       
        fi


        local foreign_key=$(prompt_for_input_with_validation "Foreign key name to define on the source model: " "Please enter foreign key" "$non_empty_regex" "please select valid foreign key") || exit $?
        status_log $TYPE_DEFAULT  "foreign_key: ${foreign_key}"

        local relation_name=$(prompt_for_input_with_validation "Relation name: " "Please enter relation name" "$non_empty_regex" "please select valid relation name") || exit $?
        status_log $TYPE_DEFAULT  "relation_name: ${relation_name}"

        local register_inclusion_resolver=$(gum choose --header "Allow Customers queries to include data from related Employees instances?" "Yes" "No") || exit $?
        status_log $TYPE_DEFAULT  "register_inclusion_resolver: ${register_inclusion_resolver}"
        
        if [ "$register_inclusion_resolver" == "Yes" ]; then
            register_inclusion_resolver=true
        else
            register_inclusion_resolver=false
        fi

        yq -i ".grapi.relations[$index].name=\"$relation_name\" | .grapi.relations[$index].name style=\"double\"" $template_file_dest
        yq -i ".grapi.relations[$index].spec.relationName=\"$relation_name\" | .grapi.relations[$index].spec.relationName style=\"double\"" $template_file_dest
        yq -i ".grapi.relations[$index].spec.destinationModel=\"$target_model\" | .grapi.relations[$index].spec.destinationModel style=\"double\"" $template_file_dest
        yq -i ".grapi.relations[$index].spec.foreignKeyName=\"$foreign_key\" | .grapi.relations[$index].spec.foreignKeyName style=\"double\"" $template_file_dest
        yq -i ".grapi.relations[$index].spec.relationType=\"$relation_type\" | .grapi.relations[$index].spec.relationType style=\"double\"" $template_file_dest
        yq -i ".grapi.relations[$index].spec.registerInclusionResolver=$register_inclusion_resolver" $template_file_dest
        
        status_log $TYPE_INFO "Do you want to add another relationship?"
        local another_rule=$(gum choose "Yes" "No") || exit $?
        
        if [ "$another_rule" == "No" ]; then
            return 0
        fi

        ((index+=1))
    

    done
    
}

take_model_input_from_cli() {
    
    MODELS=""
    models_name=()
    i=0
    while true; do

        local model_name=$(prompt_for_input_with_validation "Enter the model name: " "Please enter model name" "$non_empty_regex" "please enter valid model name") || exit $?
        status_log $TYPE_DEFAULT  "Enter the model name: ${model_name}"
        yq -i ".grapi.models[$i].name=\"$model_name\" | .grapi.models[$i].name style=\"double\"" $template_file_dest

        models_name+=("$model_name")

        local base_name=$(gum choose --header "Please select the model base class:" "Entity" "Model") || exit $?
        status_log $TYPE_DEFAULT  "Please select the model base class: ${base_name}"        
        yq -i ".grapi.models[$i].spec.base=\"$base_name\"" $template_file_dest

        id_selected=0
        while true; do

            status_log $TYPE_INFO "Let's add property to $model_name"
            status_log $TYPE_INFO "Enter an empty property name when done"

            local property_name=$(prompt_for_explicit_input_with_validation "Enter the property name: " "Please enter property name" ".*" "please enter valid property name") || exit $?
            status_log $TYPE_DEFAULT  "Enter the property name: ${property_name}"

            if [[ $property_name == "" ]]; then
                break
            fi

            local property_type=$(gum choose --header "Please select the property type" "string" "number" "boolean" "object" "array" "date" "buffer" "geopoint" "any") || exit $?
            status_log $TYPE_DEFAULT  "Enter the property type: ${property_type}"   
            yq -i ".grapi.models[$i].spec.properties.$property_name.type=\"$property_type\"" $template_file_dest

            if [ $id_selected == 0 ]; then

                is_id=$(prompt_for_input_with_validation "Is $property_name the ID property? " "(y/N)" "$non_empty_regex" "please select valid value") || exit $?
                status_log $TYPE_DEFAULT  "Is $property_name the ID property? ${is_id}"                
                if [[ $is_id == "y" || $is_id == "Y" ]]; then
                    
                    is_generated=$(prompt_for_input_with_validation "Is $property_name generated automatically? " "(y/N)" "$non_empty_regex" "please select valid value") || exit $?
                    status_log $TYPE_DEFAULT  "Is $property_name generated automatically? ${is_generated}" 
                    id_selected=1

                    yq -i ".grapi.models[$i].spec.properties.$property_name.id=true" $template_file_dest
                    yq -i ".grapi.models[$i].spec.properties.$property_name.required=true" $template_file_dest

                    if [[ $is_generated == "y" || $is_generated == "Y" ]]; then
                        yq -i ".grapi.models[$i].spec.properties.$property_name.generated=true" $template_file_dest
                    fi

                    continue
                fi
            fi

            local is_required=$(prompt_for_input_with_validation "Is it required? " "(y/N)" "$non_empty_regex" "please enter valid property name") || exit $?
            status_log $TYPE_DEFAULT  "Is it required? ${is_required}"
            if [[ $is_generated == "y" || $is_generated == "Y" ]]; then
                yq -i ".grapi.models[$i].spec.properties.$property_name.required=true" $template_file_dest
            fi

            if [[ $is_required != "y" && $is_required != "Y" ]]; then
                default_value=$(prompt_for_explicit_input_with_validation "Default value [leave blank for none]: " "enter default value" ".*" "please select valid value") || exit $?
                status_log $TYPE_DEFAULT  "Default value [leave blank for none]: ${default_value}" 
                yq -i ".grapi.models[$i].spec.properties.$property_name.defaultFn=\"$default_value\"" $template_file_dest
            fi

        done

        status_log $TYPE_INFO "Do you want to add another model?"
        local another_rule=$(gum choose "Yes" "No") || exit $?
        
        if [ "$another_rule" == "No" ]; then
            return 0
        fi

        ((i+=1))

    done
    
}

take_datasource_input_from_cli() {

    
    local ds_type=$1
    index=0

    datasource=$(prompt_for_input_with_validation "datasource: " "please provide datasource name: " "$non_empty_regex" "datasource name can't be empty")
    status_log $TYPE_DEFAULT "datasource: ${datasource}"    
    DATABASE_SCHEMA=$datasource

    url=$(prompt_for_explicit_input_with_validation "url: " "please provide url (optional): " ".*" "")
    status_log $TYPE_DEFAULT "url: ${url}"    

    host=$(prompt_for_input_with_validation "host: " "please provide host: " "$non_empty_regex" "host name can't be empty")
    status_log $TYPE_DEFAULT "host: ${host}"    

    port=$(prompt_for_input_with_validation "port: " "please provide port: " "$non_empty_regex" "port name can't be empty")
    status_log $TYPE_DEFAULT "port: ${port}"   

    user=$(prompt_for_input_with_validation "user: " "please provide user: " "$non_empty_regex" "user name can't be empty")
    status_log $TYPE_DEFAULT "user: ${user}"

    read -s -p " password: " password
    status_log $TYPE_DEFAULT 

    # yq -i ".grapi.datasources[$index].name=\"$datasource\" | .grapi.datasources[$index].name style=\"double\"" $template_file_dest
    # yq -i ".grapi.datasources[$index].spec.$ds_type.name=\"$datasource\" | .grapi.datasources[$index].spec.$ds_type.name style=\"double\"" $template_file_dest
    # yq -i ".grapi.datasources[$index].spec.$ds_type.url=\"$url\" | .grapi.datasources[$index].spec.$ds_type.url style=\"double\"" $template_file_dest
    # yq -i ".grapi.datasources[$index].spec.$ds_type.host=\"$host\" | .grapi.datasources[$index].spec.$ds_type.host style=\"double\"" $template_file_dest
    # yq -i ".grapi.datasources[$index].spec.$ds_type.port=\"$port\" | .grapi.datasources[$index].spec.$ds_type.port style=\"double\" " $template_file_dest
    # yq -i ".grapi.datasources[$index].spec.$ds_type.user=\"$user\" | .grapi.datasources[$index].spec.$ds_type.user style=\"double\"" $template_file_dest
    # yq -i ".grapi.datasources[$index].spec.$ds_type.password=\"$password\" | .grapi.datasources[$index].spec.$ds_type.password style=\"double\"" $template_file_dest
    # yq -i ".grapi.datasources[$index].spec.$ds_type.database=\"\$DATABASE_SCHEMA\"" $template_file_dest

}

take_discovery_input_from_cli() {

    index=0

    if [ "$AUTO_DISCOVERY" == "" ]; then 
    
        status_log $TYPE_INFO "Do you want the discovery to be created automatically?"
        local disc=$(gum choose "Yes" "No") || exit $?
        
        if [ "$disc" == "No" ]; then
            AUTO_DISCOVERY="false"
        else
            AUTO_DISCOVERY="true"
        fi

    fi

    
    if [ "$AUTO_DISCOVERY" == "true" ]; then
    
        yq -i ".grapi.discoveries[$index].name=\"\$DATABASE_SCHEMA\" | .grapi.discoveries[$index].name style=\"double\"" $template_file_dest
        yq -i ".grapi.discoveries[$index].spec.all=true" $template_file_dest
        yq -i ".grapi.discoveries[$index].spec.disableCamelCase=false" $template_file_dest 
        yq -i ".grapi.discoveries[$index].spec.schema=\"\$DATABASE_SCHEMA\" | .grapi.discoveries[$index].spec.schema style=\"double\"" $template_file_dest
        yq -i ".grapi.discoveries[$index].spec.dataSource=\"\$DATABASE_SCHEMA\" | .grapi.discoveries[$index].spec.dataSource style=\"double\"" $template_file_dest

    else 

        local discovery=$(prompt_for_input_with_validation "discovery: " "please provide discovery name: " "$non_empty_regex" "discovery name can't be empty")
        status_log $TYPE_DEFAULT "discovery: ${discovery}"    

        local all_models=$(prompt_for_input_with_validation "Discover all models without prompting users to select? " "(y/N)" "$non_empty_regex" "please select valid value") || exit $?
        if [[ $all_models == "y" || $all_models == "Y" ]]; then
            all="true"
        else
            all="false"
            models=$(prompt_for_explicit_input_with_validation "models: " "please provide models(optional) e.g: table1,table2: " "$.*" "")
            status_log $TYPE_DEFAULT "models: ${models}"    
        fi
        status_log $TYPE_DEFAULT "all: ${all}"  

        local disableCamelCase="false"

        local optionalId_value=$(prompt_for_input_with_validation "mark id property as optional field? " "(y/N)" "$non_empty_regex" "please select valid value") || exit $?
        if [[ $optionalId_value == "y" || $optionalId_value == "Y" ]]; then
            optionalId="true"
        else
            optionalId="false"
        fi
        status_log $TYPE_DEFAULT "optionalId: ${optionalId}"  

        local outDir=$(prompt_for_explicit_input_with_validation "outDir: " "please provide outDir(optional): " "$.*" "")
        status_log $TYPE_DEFAULT "outDir: ${outDir}"    

        local relations_value=$(prompt_for_input_with_validation "discover and create relations? " "(y/N)" "$non_empty_regex" "please select valid value") || exit $?
        if [[ $relations_value == "y" || $relations_value == "Y" ]]; then
            relations="true"
        else
            relations="false"
        fi
        status_log $TYPE_DEFAULT "relations: ${relations}"    

        local views_value=$(prompt_for_input_with_validation "discover views? " "(y/N)" "$non_empty_regex" "please select valid value") || exit $?
        if [[ $views_value == "y" || $views_value == "Y" ]]; then
            views="true"
        else
            views="false"
        fi
        status_log $TYPE_DEFAULT "views: ${views}"  

        yq -i ".grapi.discoveries[$index].name=\"$discovery\" | .grapi.discoveries[$index].name style=\"double\"" $template_file_dest
        yq -i ".grapi.discoveries[$index].spec.all=$all" $template_file_dest
        yq -i ".grapi.discoveries[$index].spec.views=$views" $template_file_dest
        yq -i ".grapi.discoveries[$index].spec.relations=$relations" $template_file_dest 
        yq -i ".grapi.discoveries[$index].spec.optionalId=$optionalId" $template_file_dest
        yq -i ".grapi.discoveries[$index].spec.disableCamelCase=$disableCamelCase" $template_file_dest 
        yq -i ".grapi.discoveries[$index].spec.schema=\"\$DATABASE_SCHEMA\" | .grapi.discoveries[$index].spec.schema style=\"double\"" $template_file_dest
        yq -i ".grapi.discoveries[$index].spec.models=\"$models\" | .grapi.discoveries[$index].spec.models style=\"double\"" $template_file_dest
        yq -i ".grapi.discoveries[$index].spec.outDir=\"$outDir\" | .grapi.discoveries[$index].spec.outDir style=\"double\"" $template_file_dest
        yq -i ".grapi.discoveries[$index].spec.dataSource=\"\$DATABASE_SCHEMA\" | .grapi.discoveries[$index].spec.dataSource style=\"double\"" $template_file_dest

    fi

}

deploy_template() {


    cli_log "resource deploy BEGIN"
    status_log $TYPE_DEFAULT "resource deploy is in progress"

    if kubectl config current-context >/dev/null 2>&1; then
        KUBE_CONTEXT=$(kubectl config current-context)
        if [ "$KUBE_CONTEXT" = "minikube" ]; then
            echo "patching for minikube..."
            MINIKUBE_PATCH=" --set gras.ssl=false --set grapi.ssl=false --set gruim.ssl=false "
        else
            MINIKUBE_PATCH=""
        fi
    fi

    if ! eval "$(getGumSpinnerOrLogger "Deploying template") helm upgrade --install ${GRAS_NAME} oci://public.ecr.aws/${awsregistry}/gras-deploy  -n ${KUBE_NS} -f $template_file_dest ${MINIKUBE_PATCH}"; then
        status_log $TYPE_ERROR "Failed to deploy template due to following error"
        errMsg=$(helm upgrade --install ${GRAS_NAME} oci://public.ecr.aws/${awsregistry}/gras-deploy  -n ${KUBE_NS} -f $template_file_dest ${MINIKUBE_PATCH})
        status_log $TYPE_ERROR "${errMsg}"
        exit 1
    fi
    
    status_log $TYPE_INFO "wait for $GRAS_NAME to be ready" 
    CRD="gras" && echo "Wait for $CRD to be deployed:" && SECONDS=0 && TIMEOUT=60 && until kubectl get $CRD -n $KUBE_NS | awk '{print $3}' | grep -q True >/dev/null 2>&1 || [ $SECONDS -ge $TIMEOUT ]; do echo -n .; sleep 1; done && if [ $SECONDS -ge $TIMEOUT ]; then status_log $TYPE_ERROR "Timeout exceeded, $CRD not deployed after 1 minute"; exit 1; else echo "$CRD deployed"; fi
    status_log $TYPE_SUCCESS "$CRD deployed"

}

check_and_create_kubens() {

    if [[ "$KUBE_NS" != "" ]] && ! kubectl get namespace "$KUBE_NS" >/dev/null 2>&1; then
        status_log $TYPE_INFO "namespace $KUBE_NS doesn't exist, now creating"
        kubectl create namespace "$KUBE_NS"
    elif [[ "$KUBE_NS" == "" ]]; then
        status_log $TYPE_INFO "Do you want to select existing namespace or create new one?"
        local another_rule=$(gum choose "Select from existing" "Create new") || exit $?
        
        if [ "$another_rule" == "Select from existing" ]; then
            namespaces=$(kubectl get namespaces -o name | awk -F'/' '{print $2}')
            current_ns="default"
            KUBE_NS=$(if [ "${KUBE_NS}" != "" ]; then echo ${KUBE_NS}; else gum choose  --header "Please select kubectl namespace you want to use" $namespaces --selected=$current_ns ; fi) || exit $?
        else
            KUBE_NS=$(if [ "${KUBE_NS}" != "" ]; then echo ${KUBE_NS}; else prompt_for_explicit_input_with_validation "Enter KUBE_NS: " "default value is '$GRAS_NAME'" ".*" "kube ns can't be empty"; fi) || exit $?
            if [ "${KUBE_NS}" == "" ]; then KUBE_NS=$GRAS_NAME; fi
            if ! kubectl get namespace "$KUBE_NS" >/dev/null 2>&1; then
                    status_log $TYPE_INFO "namespace $KUBE_NS doesn't exist, now creating"
                    kubectl create namespace "$KUBE_NS"
            fi
        fi    
    fi
}

ask_guim_enablement(){

    status_log $TYPE_DEFAULT "Do you want enable gruim?"
    ENABLE_GRUIM=$(if [ "${ENABLE_GRUIM}" != "" ]; then echo ${ENABLE_GRUIM}; else  gum choose "Yes" "No"; fi) || exit $?
    status_log $TYPE_DEFAULT "ENABLE_GRUIM: ${ENABLE_GRUIM}"
    
    if [ "$ENABLE_GRUIM" == "No" ]; then
        yq eval 'del(.gruims)' -i $template_file_dest
    fi

}

take_db_file_path() {
    DB_FILE_PATH=$(if [ "${DB_FILE_PATH}" != "" ]; then echo ${DB_FILE_PATH}; else prompt_for_explicit_input_with_validation "Enter DB_FILE_PATH: " "Provide file path where you want to store data, default value is $db_file_default_value" "$abs_path_regex" "please provide correct absolute file path"; fi) || exit $?
    if [ "${DB_FILE_PATH}" == "" ]; then 
        DB_FILE_PATH=$db_file_default_value
    fi
    status_log $TYPE_DEFAULT "DB_FILE_PATH: ${DB_FILE_PATH}"
    export db_file=$DB_FILE_PATH
}


substitute_env_vars_in_template() {

    check_and_install_gettext
    envsubst < "$template_file_dest" > "$tmp_file_dest" && mv "$tmp_file_dest" "$template_file_dest"

}

add_datasource_config_to_template() {

    ds_type=$1

    local url=$2
    local host="\$(host)"
    local port="\$(port)"
    local user="\$(username)"
    local password="\$(password)"
    index=0
    yq -i ".grapi.datasources[$index].name=\"\$DATABASE_SCHEMA\" | .grapi.datasources[$index].name style=\"double\"" $template_file_dest
    yq -i ".grapi.datasources[$index].spec.$ds_type.name=\"\$DATABASE_SCHEMA\" | .grapi.datasources[$index].spec.$ds_type.name style=\"double\"" $template_file_dest
    yq -i ".grapi.datasources[$index].spec.$ds_type.url=\"$url\" | .grapi.datasources[$index].spec.$ds_type.url style=\"double\"" $template_file_dest
    yq -i ".grapi.datasources[$index].spec.$ds_type.host=\"$host\" | .grapi.datasources[$index].spec.$ds_type.host style=\"double\"" $template_file_dest
    yq -i ".grapi.datasources[$index].spec.$ds_type.port=\"$port\" | .grapi.datasources[$index].spec.$ds_type.port style=\"double\"" $template_file_dest
    yq -i ".grapi.datasources[$index].spec.$ds_type.user=\"$user\" | .grapi.datasources[$index].spec.$ds_type.user style=\"double\"" $template_file_dest
    yq -i ".grapi.datasources[$index].spec.$ds_type.password=\"$password\" | .grapi.datasources[$index].spec.$ds_type.password style=\"double\"" $template_file_dest
    yq -i ".grapi.datasources[$index].spec.$ds_type.database=\"\$DATABASE_SCHEMA\"" $template_file_dest

}

# ----------------------- functions code ended ---------------------

# ------------------------------------------------------------------

# ---------------- first check for input params --------------------

# valid arguments array
valid_args=(
    "KUBE_CONTEXT"
    "GRAS_NAME"
    "GRAS_TEMPLATE"
    "SOURCE_DATA"
    "DB_FILE_PATH"
    "DB_TYPE"
    "ENABLE_GRUIM"
    "MODELS"
    "RELATIONS"
    "KUBE_NS"
    "DATASOURCES"
    "DISCOVERIES"
    "DATABASE_SCHEMA"
    "AUTO_DISCOVERY"
  )

# check if values are already passed form terminal
# if yes? then store then in the respective vars
extract_input_params_from_cli $valid_args "grpl r d h" $(echo "$@")

#---------- KUBE_CONTEXT Input ------------

if [ -n "$KUBERNETES_SERVICE_HOST" ] && [ -n "$KUBERNETES_SERVICE_PORT" ]; then
    echo "Running inside a Kubernetes cluster"
else
    echo "Not running inside a Kubernetes cluster"
    if [ "${KUBE_CONTEXT}" == $CURRENT_CONTEXT ] || [ "${KUBE_CONTEXT}" == "" ]; then
        if kubectl config current-context >/dev/null 2>&1; then
        KUBE_CONTEXT=$(kubectl config current-context)
        fi
    fi
    
    # Run the command and store the output in a variable
    contexts=$(kubectl config get-contexts -o name)
    # Check if the output is empty
    if [ -z "$contexts" ]; then
        status_log $TYPE_ERROR "Error: No contexts found"
        exit 1
    else
        #check if input from params is valid or not
        is_correct_kubectl_context_provided $KUBE_CONTEXT
        contexts=$(kubectl config get-contexts -o name)
        KUBE_CONTEXT=$(if [ "${KUBE_CONTEXT}" != "" ]; then echo ${KUBE_CONTEXT}; else gum choose  --header "Please select kubectl context you want to use" $contexts ; fi) || exit $?
        kubectl config use-context $KUBE_CONTEXT
        status_log $TYPE_DEFAULT "KUBE_CONTEXT: ${KUBE_CONTEXT}"
    fi
fi



#check if input from params is valid or not
if [ "${GRAS_NAME}" != "" ]; then 
  is_value_correct_wrt_regex $GRAS_NAME $alphaNum_plus_hyphen_and_underscope_regex "gras name can only contain alpha numaric characters, '-'and '_' as special characters"
fi
GRAS_NAME=$(if [ "${GRAS_NAME}" != "" ]; then echo ${GRAS_NAME}; else prompt_for_input_with_validation "Enter GRAS_NAME: " "Provide gras name" "$alphaNum_plus_hyphen_and_underscope_regex" "gras name can only contain alpha numaric characters, '-' and '_' as special characters"; fi) || exit $?
status_log $TYPE_DEFAULT "GRAS_NAME: ${GRAS_NAME}"

#check if input from params is valid or not
if [ "${GRAS_TEMPLATE}" != "" ]; then 
  is_correct_grapple_applicationsets_provided $GRAS_TEMPLATE 
fi
GRAS_TEMPLATE=$(if [ "${GRAS_TEMPLATE}" != "" ]; then echo ${GRAS_TEMPLATE}; else gum choose  --header "Please select template you want create" $DB_FILE $DB_MYSQL_MODEL_BASED $DB_MYSQL_DISCOVERY_BASED; fi) || exit $?
status_log $TYPE_DEFAULT "GRAS_TEMPLATE: ${GRAS_TEMPLATE}"


check_and_create_kubens

# ----------------------- params code ended ---------------------------



if [ "$GRAS_TEMPLATE" == "$DB_FILE" ]; then

    template_file_dest="/tmp/db-file.yaml"
    db_file_default_value=/data/db.json
    cp "$GRPL_WORKDIR/template-files/db-file.yaml" $template_file_dest

    # input model
    if [[ $MODELS == "" ]]; then
        take_model_input_from_cli
    else 
        # the input model should look like this
        # 'customers:{"base":"Entity","name":"customers","properties":{"city":{"type":"string"},"generatedValue":{"generated":true,"defaultFn":999,"id":false,"required":true,"type":"number"}}}|employees:{"base":"Entity","name":"employees","properties":{"country":{"type":"string"},"creditLimit":{"type":"number"}}}'
        transform_model_input_to_yaml $MODELS
    fi 


    take_db_file_path

    # input data source url
    SOURCE_DATA=$(if [ "${SOURCE_DATA}" != "" ]; then echo ${SOURCE_DATA}; else prompt_for_explicit_input_with_validation "Enter SOURCE_DATA: " "Provide data source url, press enter to omit" ".*" "please provide valid datasource url"; fi) || exit $?
    if [[ $SOURCE_DATA != "" ]]; then
        status_log $TYPE_DEFAULT "SOURCE_DATA: ${SOURCE_DATA}"
        export testdata_url=$SOURCE_DATA
    else
        yq eval 'del(.grapi.initContainers)' -i $template_file_dest
    fi


    cli_args=$@
    if [[ "${cli_args[@]}" =~ "--RELATIONS" ]] && [[ $RELATIONS == "" ]] ; then
        yq eval 'del(.grapi.relations)' -i $template_file_dest
    else
        take_relation_input_from_cli "${models_name[@]}"
    fi
    

    ask_guim_enablement

    substitute_env_vars_in_template

    # at this point our template manifest is ready at /tmp/db-file.yaml
    # we'll deploy it now
    deploy_template

    # now remove the tmp file
    rm $template_file_dest
    
    exit 1
fi

# for all other cases
template_file_dest="/tmp/db.yaml"
kubeblocks_template_file_dest="/tmp/kube_db.yaml"
cp "$GRPL_WORKDIR/template-files/db.yaml" $template_file_dest
cp "$GRPL_WORKDIR/files/db.yaml" $kubeblocks_template_file_dest

#check if input from params is valid or not
if [ "${DB_TYPE}" != "" ]; then 
  is_correct_db_type_provided $DB_TYPE 
fi
DB_TYPE=$(if [ "${DB_TYPE}" != "" ]; then echo ${DB_TYPE}; else gum choose  --header "Please select the database type you want" $INTERNAL_DB $EXTERNAL_DB; fi) || exit $?
status_log $TYPE_DEFAULT "DB_TYPE: ${DB_TYPE}"

# internal/external db case
if [[ $DB_TYPE == "$INTERNAL_DB" ]]; then

    # check if kubeblocks is installed
    if ! kbcli cluster list -n ${KUBE_NS} ${GRAS_NAME} >/dev/null 2>&1; then
        yq -i ".metadata.name=\"$GRAS_NAME\"" $kubeblocks_template_file_dest
        kubectl apply -n ${KUBE_NS} -f $kubeblocks_template_file_dest
        status_log $TYPE_INFO "created internal db"
    fi

    if [[ "$GRAS_TEMPLATE" == "$DB_MYSQL_MODEL_BASED"  ]] || [[ "$GRAS_TEMPLATE" == "$DB_MYSQL_DISCOVERY_BASED"  ]]; then
        add_datasource_config_to_template "mysql"
    fi

    #updating secrets name
    yq -i ".grapi.extraSecrets[0]=\"$GRAS_NAME-conn-credential\"" $template_file_dest


elif [[ $DB_TYPE == "$EXTERNAL_DB" ]]; then

    # get datasources details either from params or cli
    if [[ $DATASOURCES != "" ]]; then
        transform_datasources_input_to_yaml $DATASOURCES
    else
        if [[ "$GRAS_TEMPLATE" == "$DB_MYSQL_MODEL_BASED"  ]] || [[ "$GRAS_TEMPLATE" == "$DB_MYSQL_DISCOVERY_BASED"  ]]; then
            take_datasource_input_from_cli "mysql"
        fi
    fi 
 
    # update the template with datasources
    if [[ "$GRAS_TEMPLATE" == "$DB_MYSQL_MODEL_BASED"  ]] || [[ "$GRAS_TEMPLATE" == "$DB_MYSQL_DISCOVERY_BASED"  ]]; then
        add_datasource_config_to_template "mysql" $url
    fi


    # now create secret to store the creds
    SECRET_NAME="${GRAS_NAME}-conn-credential"

    # Check if the secret exists
    if kubectl get secret "${SECRET_NAME}" -n "${KUBE_NS}" >/dev/null 2>&1; then
        echo "Secret ${SECRET_NAME} exists. Deleting it..."
        kubectl delete secret "${SECRET_NAME}" -n "${KUBE_NS}"
        if [ $? -eq 0 ]; then
            echo "Secret ${SECRET_NAME} deleted successfully."
        else
            status_log $TYPE_ERROR "Failed to delete secret ${SECRET_NAME}."
            status_log $TYPE_ERROR "Failed to deploy resource"
            exit 1
        fi
    else
        echo "Secret ${SECRET_NAME} does not exist. Proceeding to create it..."
    fi

    # Create the secret
    echo "Creating secret ${SECRET_NAME}..."
    kubectl create secret generic "${SECRET_NAME}" \
    --from-literal=host="${host}" \
    --from-literal=password="${password}" \
    --from-literal=port="${port}" \
    --from-literal=username="${user}" \
    -n "${KUBE_NS}"

    if [ $? -eq 0 ]; then
        echo "Secret ${SECRET_NAME} created successfully in namespace ${KUBE_NS}."
    else
        status_log $TYPE_ERROR "Failed to create secret ${SECRET_NAME}."
        status_log $TYPE_ERROR "Failed to deploy resource"
        exit 1
    fi


    yq -i ".grapi.extraSecrets[0]=\"$SECRET_NAME\"" $template_file_dest


    # TODO: Check if data source connection details are correct or not

fi

# discovery based checks
if [[ "$GRAS_TEMPLATE" == "$DB_MYSQL_DISCOVERY_BASED"  ]]; then
    
    if [[ "$DISCOVERIES" != "" ]]; then
        transform_discoveries_input_to_yaml $DISCOVERIES
    else
        take_discovery_input_from_cli
    fi

    yq -i ".grapi.discoveredrepos=true" $template_file_dest

elif  [[ "$GRAS_TEMPLATE" == "$DB_MYSQL_MODEL_BASED"  ]]; then
    # input model
    if [[ $MODELS == "" ]]; then
        take_model_input_from_cli
    else 
        # the input model should look like this
        # 'customers:{"base":"Entity","name":"customers","properties":{"city":{"type":"string"},"generatedValue":{"generated":true,"defaultFn":999,"id":false,"required":true,"type":"number"}}}|employees:{"base":"Entity","name":"employees","properties":{"country":{"type":"string"},"creditLimit":{"type":"number"}}}'
        transform_model_input_to_yaml $MODELS
    fi 

    yq -i ".grapi.automigrate=true" $template_file_dest

fi

cli_args=$@
if [[ "${cli_args[@]}" =~ "--RELATIONS" ]] && [[ $RELATIONS == "" ]] ; then
    yq eval 'del(.grapi.relations)' -i $template_file_dest
else
    take_relation_input_from_cli "${models_name[@]}"
fi

DATABASE_SCHEMA=$(if [ "${DATABASE_SCHEMA}" != "" ]; then echo ${DATABASE_SCHEMA}; else prompt_for_input_with_validation "DATABASE_SCHEMA: " "please provide DATABASE SCHEMA: " "$non_empty_regex" "DATABASE_SCHEMA name can'tdi be empty"; fi) || exit $?
status_log $TYPE_DEFAULT "DATABASE_SCHEMA: ${DATABASE_SCHEMA}"
export DATABASE_SCHEMA=$DATABASE_SCHEMA

# check for init-containers
cli_args=$@
# if SOURCE_DATA is explicitly set to empty
if [[ "${cli_args[@]}" =~ "--SOURCE_DATA" ]] && [[ $SOURCE_DATA == "" ]] ; then
    mysql_init_container_bash_script="sleep 5; while ! mysql -h \$(host) -P \$(port) -u \$(username) -p\$(password) -e \\\"show databases;\\\" 2>/dev/null; do echo -n .; sleep 2; done; mysql -h \$(host) -P \$(port) -u \$(username) -p\$(password) -e \\\"CREATE DATABASE IF NOT EXISTS ${DATABASE_SCHEMA};\\\";"
    yq -i ".grapi.initContainers[0].spec.image=\"mysql\"" $template_file_dest
    export command=$mysql_init_container_bash_script
else

    mysql_init_container_bash_script=""

    # input data source url if not given
    SOURCE_DATA=$(if [ "${SOURCE_DATA}" != "" ]; then echo ${SOURCE_DATA}; else prompt_for_explicit_input_with_validation "Enter SOURCE_DATA: " "Provide data source url, press enter to omit" ".*" "please provide valid datasource url"; fi) || exit $?
    if [[ $SOURCE_DATA != "" ]]; then
        status_log $TYPE_DEFAULT "SOURCE_DATA: ${SOURCE_DATA}"
        export testdata_url=$SOURCE_DATA
        
        mysql_init_container_bash_script="sleep 5; while ! mysql -h \$(host) -P \$(port) -u \$(username) -p\$(password) -e \\\"show databases;\\\" 2>/dev/null; do echo -n .; sleep 2; done; if mysql -h \$(host) -P \$(port) -u \$(username) -p\$(password) -e \\\"USE $DATABASE_SCHEMA; SET @tablename := (select table_name from information_schema.tables where table_type = 'BASE TABLE' and table_schema = '$DATABASE_SCHEMA' limit 1); set @qry1:= concat('select * from ',@tablename,' limit 1'); prepare stmt from @qry1 ; execute stmt ;\\\" ; then echo \\\"database already exists...\\\"; else curl -o /tmp/$DATABASE_SCHEMA.sql $SOURCE_DATA; mysql -h \$(host) -P \$(port) -u \$(username) -p\$(password) < /tmp/$DATABASE_SCHEMA.sql; fi;"
        yq -i ".grapi.initContainers[0].spec.image=\"mysql\"" $template_file_dest
        export command=$mysql_init_container_bash_script
    else
        mysql_init_container_bash_script=""
        mysql_init_container_bash_script="sleep 5; while ! mysql -h \$(host) -P \$(port) -u \$(username) -p\$(password) -e \\\"show databases;\\\" 2>/dev/null; do echo -n .; sleep 2; done; mysql -h \$(host) -P \$(port) -u \$(username) -p\$(password) -e \\\"CREATE DATABASE IF NOT EXISTS ${DATABASE_SCHEMA};\\\";"
        yq -i ".grapi.initContainers[0].spec.image=\"mysql\"" $template_file_dest
        export command=$mysql_init_container_bash_script
    fi


fi


ask_guim_enablement
substitute_env_vars_in_template
# at this point our template manifest is ready at /tmp/db.yaml
# we'll deploy it now
deploy_template
