apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    kubefirst.dev:53 {
        template IN A {
            match ^(?P<sub>.+)\.kubefirst\.dev\.$
            answer "{{.Name}} 60 IN A $DOCKER_API_GATEWAY"
        }
        template IN AAAA {
            match ^(?P<sub>.+)\.kubefirst\.dev\.$
            answer "{{.Name}} 60 IN AAAA ::1"
        }
        log
    }
    k3d.dev:53 {
        template IN A {
            match ^(?P<sub>.+)\.k3d\.dev\.$
            answer "{{.Name}} 60 IN A $DOCKER_API_GATEWAY"
        }
        template IN AAAA {
            match ^(?P<sub>.+)\.k3d\.dev\.$
            answer "{{.Name}} 60 IN AAAA ::1"
        }
        log
    }
 

