#!/bin/bash
set -e
. "$GRPL_WORKDIR/common"

cli_help_cluster_status() {
  echo "
Command: cluster status

Usage: 
  cluster status"
  exit 1
}

[ ! -n "$1" ] && cli_help_cluster_status

export BAGCLI_PROJECT_NAME=$1

cli_log "cluster status BEGIN"



cli_log "cluster status END"
