#!/bin/bash
set -e
set -o pipefail
. "$GRPL_WORKDIR/utils/help_menus"

cli_help() {
  grpl_cluster_status_cli_help
  exit 0
}

[ "$1" = "help" ] || [ "$1" = "h" ] && cli_help


cli_log "cluster status BEGIN"



cli_log "cluster status END"
