name: PR Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the current branch's code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install bats
      - name: Install bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      # Install kubectl
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      # Install civo cli
      - name: Install civo cli
        run: |
          curl -sL https://civo.com/get | sh

      # Install Homebrew
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      # Copy the current branch's code to a writable path
      - name: Setup Executable Path for CLI
        run: |
          echo "Setting up code for CLI..."
          sudo cp -r $GITHUB_WORKSPACE /tmp/grpl-cli
          sudo chmod -R u+w /tmp/grpl-cli
          ln -sf /tmp/grpl-cli/grpl /usr/local/bin/grpl
          export PATH="/usr/local/bin:$PATH"
          echo "Testing grpl CLI..."
          grpl

      # Run bash tests
      - name: Run Bash Tests
        env:
          CIVO_API_KEY: ${{ secrets.CIVO_API_KEY }}
          OSTYPE: darwin23.0
        run: |
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

          echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bashrc
          export PATH="/usr/local/bin:$PATH"
          source ~/.bashrc
          bats test
